/** 100 witzige Fantasienamen für leere Spielerfelder */
window.FANTASY_NAMES = [
  "Würfelbert",
  "Paschula",
  "Glücksfrida",
  "Zonkzilla",
  "Punktine",
  "Rundenritter",
  "Augenauf",
  "Sechserfee",
  "EinsamEins",
  "Haltehans",
  "Risikoraoul",
  "Bankerin Berta",
  "Tischkönig",
  "Bechernicht",
  "Volltreffer Vera",
  "Niete Norma",
  "Chance Charlie",
  "Kesselchen Kai",
  "Doppel-Doris",
  "Triplet Tim",
  "Viererfritz",
  "Fünferfred",
  "Sechser-Susi",
  "Joker Johanna",
  "Bluff Boris",
  "Pokerface Pia",
  "Schummel-Sven",
  "Ehrlicher Emil",
  "Nervennadel",
  "Cooler Klaus",
  "Hitzkopf Heidi",
  "Pechvogel Paul",
  "Fortuna Fanny",
  "Zufalls-Zack",
  "Würfelwurm",
  "Augenarbeiter",
  "Punktesammler",
  "Summen-Sophie",
  "Total-Theo",
  "Zwischenstand Zoe",
  "Endspurt Edda",
  "Nachzügler Nico",
  "Vorsprung Volker",
  "Gleichstand Greta",
  "Knapp daneben",
  "Voll daneben",
  "Fast geschafft",
  "Noch ein Mal",
  "Letzte Runde",
  "Alles oder nix",
  "Halbe Portion",
  "Große Klappe",
  "Leise Liesel",
  "Laut Leo",
  "Zitterfinger",
  "Ruhige Hand",
  "Schnelle Sophie",
  "Bedenkzeit Ben",
  "Tipp-Tipp Tina",
  "OK-Otto",
  "Lösch-Lotte",
  "Menü-Maria",
  "Dreher Dieter",
  "Gegensitzer",
  "Nebensitzer",
  "Tischmitte",
  "Kantenkönig",
  "Glasgecko",
  "Neon-Nora",
  "Samt-Stefan",
  "Filz-Felix",
  "Plüsch-Pauline",
  "Keks-Karla",
  "Brezel-Bruno",
  "Salzbrezel",
  "Zuckerstück",
  "Pfefferminz",
  "Lakritz-Lars",
  "Marzipan Max",
  "Schokoschock",
  "Vanille-Vera",
  "Zitronenzorn",
  "Himbeerheld",
  "Blaubeerbert",
  "Erdbeer-Erna",
  "Kirschenklaus",
  "Apfelalarm",
  "Birnenbeben",
  "Pflaumenplan",
  "Traubentrupp",
  "Melonenmut",
  "Ananasangst",
  "Kokoschaos",
  "Bananenbluff",
  "Kiwi-Krise",
  "Mango-Macht",
  "Drachenfrucht",
  "Sternenfrucht",
  "Glücksklee",
  "Hufeisen Heidi",
];
